import { IBlog, fetchBlogs } from '@/apicalls/blog';
import BlogContent from '@/components/BlogContent'
import SectionFilter from '@/components/SectionFilter'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import { Header, Icon } from 'semantic-ui-react'

export const dropdownSections = [
  {
      key: 'all',
      text: 'all',
      value: 'all',
  },
  {
      key: 'american',
      text: 'american',
      value: 'american',
  },
  {
      key: 'french',
      text: 'french',
      value: 'french',
  },
  {
      key: 'history',
      text: 'history',
      value: 'history',
  },
  {
      key: 'crime',
      text: 'crime',
      value: 'crime',
  },
  {
      key: 'love',
      text: 'love',
      value: 'love',
  }

]

export default function Home() {
  const [filterValue, setFilterValue] = useState('all');
  const filterChanged = (value: string) => {
    setFilterValue(value);
  }
  const [blogs, setBlogs] = useState<IBlog[]>([]);

    useEffect(() => {

        fetchBlogs(setBlogs);

    }, []);


    return (
    <>
      <Head>
        <title>Tiny Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="home-main">
        <Header className="home-header" as='h1' icon textAlign='center' inverted color='pink'>
          <Icon name='blogger' />
          <Header.Content>Welcome to Tiny Blog</Header.Content>
        </Header>
        <div>
          <SectionFilter filterChanged={filterChanged} />
        </div>
        <div className="home-body-container">
          <BlogContent blogs={blogs} filterValue={filterValue} />
        </div>
      </main>
    </>
  )
}
